OBJS = src/JSORONParser.cpp test/JSORONParser_main.cpp

CC = g++

COMPILER_FLAGS = 

INCLUDE_DIR = include

DEBUG_FLAG = -g

OBJ_NAME = build/JSORONParser

all: $(OBJS)
	$(CC) $(COMPILER_FLAGS) $(DEBUG_FLAG) -o $(OBJ_NAME) $(OBJS) -I $(INCLUDE_DIR)
	
